class(1).id = '00';     class(1).desc = 'speed limit 20';                           class(1).type = 'prohibitory';  class(1).shape = 'circle';
class(2).id = '01';     class(2).desc = 'speed limit 30';                           class(2).type = 'prohibitory';  class(2).shape = 'circle';
class(3).id = '02';     class(3).desc = 'speed limit 50';                           class(3).type = 'prohibitory';  class(3).shape = 'circle';
class(4).id = '03';     class(4).desc = 'speed limit 60';                           class(4).type = 'prohibitory';  class(4).shape = 'circle';
class(5).id = '04';     class(5).desc = 'speed limit 70';                           class(5).type = 'prohibitory';  class(5).shape = 'circle';
class(6).id = '05';     class(6).desc = 'speed limit 80';                           class(6).type = 'prohibitory';  class(6).shape = 'circle';
class(7).id = '06';     class(7).desc = 'restriction ends 80';                      class(7).type = 'other';        class(7).shape = 'circle';
class(8).id = '07';     class(8).desc = 'speed limit 100';                          class(8).type = 'prohibitory';  class(8).shape = 'circle';
class(9).id = '08';     class(9).desc = 'speed limit 120';                          class(9).type = 'prohibitory';  class(9).shape = 'circle';
class(10).id = '09';    class(10).desc = 'no overtaking';                           class(10).type = 'prohibitory'; class(10).shape = 'circle';
class(11).id = '10';    class(11).desc = 'no overtaking (trucks)';                  class(11).type = 'prohibitory'; class(11).shape = 'circle';
class(12).id = '11';    class(12).desc = 'priority at next intersection';           class(12).type = 'danger';      class(12).shape = 'triangle';
class(13).id = '12';    class(13).desc = 'priority road';                           class(13).type = 'other';       class(13).shape = 'rhombus';
class(14).id = '13';    class(14).desc = 'give way';                                class(14).type = 'other';       class(14).shape = 'triangle180';
class(15).id = '14';    class(15).desc = 'stop';                                    class(15).type = 'other';       class(15).shape = 'octagon';
class(16).id = '15';    class(16).desc = 'no traffic both ways';                    class(16).type = 'prohibitory'; class(16).shape = 'circle';
class(17).id = '16';    class(17).desc = 'no trucks';                               class(17).type = 'prohibitory'; class(17).shape = 'circle';
class(18).id = '17';    class(18).desc = 'no entry';                                class(18).type = 'other';       class(18).shape = 'circle';
class(19).id = '18';    class(19).desc = 'danger';                                  class(19).type = 'danger';      class(19).shape = 'triangle';
class(20).id = '19';    class(20).desc = 'bend left';                               class(20).type = 'danger';      class(20).shape = 'triangle';
class(21).id = '20';    class(21).desc = 'bend right';                              class(21).type = 'danger';      class(21).shape = 'triangle';
class(22).id = '21';    class(22).desc = 'bend';                                    class(22).type = 'danger';      class(22).shape = 'triangle';
class(23).id = '22';    class(23).desc = 'uneven road';                             class(23).type = 'danger';      class(23).shape = 'triangle';
class(24).id = '23';    class(24).desc = 'slippery road';                           class(24).type = 'danger';      class(24).shape = 'triangle';
class(25).id = '24';    class(25).desc = 'road narrows';                            class(25).type = 'danger';      class(25).shape = 'triangle';
class(26).id = '25';    class(26).desc = 'construction';                            class(26).type = 'danger';      class(26).shape = 'triangle';
class(27).id = '26';    class(27).desc = 'traffic signal';                          class(27).type = 'danger';      class(27).shape = 'triangle';
class(28).id = '27';    class(28).desc = 'pedestrian crossing';                     class(28).type = 'danger';      class(28).shape = 'triangle';
class(29).id = '28';    class(29).desc = 'school crossing';                         class(29).type = 'danger';      class(29).shape = 'triangle';
class(30).id = '29';    class(30).desc = 'cycles crossing';                         class(30).type = 'danger';      class(30).shape = 'triangle';
class(31).id = '30';    class(31).desc = 'snow';                                    class(31).type = 'danger';      class(31).shape = 'triangle';
class(32).id = '31';    class(32).desc = 'animals';                                 class(32).type = 'danger';      class(32).shape = 'triangle';
class(33).id = '32';    class(33).desc = 'restriction ends';                        class(33).type = 'other';       class(33).shape = 'circle';
class(34).id = '33';    class(34).desc = 'go right';                             	class(34).type = 'mandatory';   class(34).shape = 'circle';
class(35).id = '34';    class(35).desc = 'go left';                                 class(35).type = 'mandatory';   class(35).shape = 'circle';
class(36).id = '35';    class(36).desc = 'go straight';                             class(36).type = 'mandatory';   class(36).shape = 'circle';
class(37).id = '36';    class(37).desc = 'go right or straight';                    class(37).type = 'mandatory';   class(37).shape = 'circle';
class(38).id = '37';    class(38).desc = 'go left or straight';                     class(38).type = 'mandatory';   class(38).shape = 'circle';
class(39).id = '38';    class(39).desc = 'keep right';                              class(39).type = 'mandatory';   class(39).shape = 'circle';
class(40).id = '39';    class(40).desc = 'keep left';                               class(40).type = 'mandatory';   class(40).shape = 'circle';
class(41).id = '40';    class(41).desc = 'roundabout';                              class(41).type = 'mandatory';   class(41).shape = 'circle';
class(42).id = '41';    class(42).desc = 'restriction ends (overtaking)';           class(42).type = 'other';       class(42).shape = 'circle';
class(43).id = '42';    class(43).desc = 'restriction ends (overtaking (trucks))';  class(43).type = 'other';       class(43).shape = 'circle';