imageFiles = dir([train_dir,'/*.ppm']);
i = 1;

for imageFile = imageFiles'
    imageFile
    [   detected(i).I,...
        detected(i).bbox_circle,...
        detected(i).bbox_triangle,...
        detected(i).bbox_rhombus,...
        detected(i).bbox_triangle180,...
        detected(i).bbox_octagon ] = detect(data,train_dir,imageFile.name);
    i = i +1;
end